name: CI/CD → Tomcat Deploy

on:
  push:
    branches: [ main, 'feature-*' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Deploy WAR to TomcatS
        env:
          TOMCAT_USERNAME: admin          # 🔁 thay bằng username thật
          TOMCAT_PASSWORD: admin123       # 🔁 thay bằng mật khẩu thật
          TOMCAT_HOST: localhost8080.com       # 🔁 không dùng localhost
          TOMCAT_PORT: 80                 # hoặc 443 nếu dùng HTTPS
        run: |
          curl -v -u $admin:$admin123 \
            -T target/*.war \
            "http://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/baitapnhom5&update=true"
